#!/usr/bin/env node

/**
 * ScribeAI Setup Script
 * 
 * Automated development environment setup with dependency installation,
 * environment configuration, and database initialization.
 * 
 * @author ScribeAI Team
 * @version 1.0.0
 */

const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')
const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

console.log('🚀 ScribeAI Development Setup')
console.log('=================================\n')

/**
 * Execute shell command with error handling
 */
function runCommand(command, description) {
  try {
    console.log(`📦 ${description}...`)
    execSync(command, { stdio: 'inherit' })
    console.log(`✅ ${description} completed\n`)
  } catch (error) {
    console.error(`❌ ${description} failed:`, error.message)
    process.exit(1)
  }
}

/**
 * Create environment file from template
 */
function createEnvFile() {
  const envPath = path.join(__dirname, '.env.local')
  
  if (fs.existsSync(envPath)) {
    console.log('✅ .env.local already exists\n')
    return
  }
  
  console.log('📝 Creating environment configuration...')
  
  const envTemplate = `# ScribeAI Environment Configuration
# Generated by setup script on ${new Date().toISOString()}

# Database Configuration
DATABASE_URL="postgresql://postgres:1234@localhost:5432/ScribeAI"

# Gemini AI Configuration  
# Get your API key from: https://aistudio.google.com/apikey
GEMINI_API_KEY="your_gemini_api_key_here"

# Authentication
NEXTAUTH_SECRET="a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"

# Server Configuration
SOCKET_SERVER_URL="http://localhost:3001"
NEXT_PUBLIC_SOCKET_URL="http://localhost:3001"
PORT=3001

# Development Settings
NODE_ENV="development"
`

  fs.writeFileSync(envPath, envTemplate)
  console.log('✅ Created .env.local\n')
  console.log('⚠️  IMPORTANT: Update .env.local with your actual Gemini API key!')
  console.log('   Get yours at: https://aistudio.google.com/apikey\n')
}

/**
 * Check if required tools are installed
 */
function checkPrerequisites() {
  console.log('🔍 Checking prerequisites...')
  
  try {
    execSync('node --version', { stdio: 'pipe' })
    console.log('✅ Node.js is installed')
  } catch {
    console.error('❌ Node.js is required. Install from: https://nodejs.org/')
    process.exit(1)
  }
  
  try {
    execSync('npm --version', { stdio: 'pipe' })
    console.log('✅ npm is available')
  } catch {
    console.error('❌ npm is required')
    process.exit(1)
  }
  
  // Check if PostgreSQL is running (optional check)
  try {
    execSync('psql --version', { stdio: 'pipe' })
    console.log('✅ PostgreSQL is installed')
  } catch {
    console.log('⚠️  PostgreSQL not found - you\'ll need it for the database')
    console.log('   Install from: https://www.postgresql.org/download/')
  }
  
  console.log('✅ Prerequisites check completed\n')
}

/**
 * Main setup process
 */
async function setupProject() {
  try {
    // Check prerequisites
    checkPrerequisites()
    
    // Install frontend dependencies
    runCommand('npm install', 'Installing frontend dependencies')
    
    // Install server dependencies
    runCommand('cd server && npm install', 'Installing server dependencies')
    
    // Create environment file
    createEnvFile()
    
    // Generate Prisma client
    runCommand('npx prisma generate', 'Generating Prisma client')
    
    // Optional: Setup database (requires PostgreSQL)
    console.log('🗄️  Database setup...')
    
    const shouldSetupDB = await new Promise(resolve => {
      rl.question('Setup database now? (y/N): ', (answer) => {
        resolve(answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes')
      })
    })
    
    if (shouldSetupDB) {
      try {
        runCommand('npx prisma db push', 'Setting up database schema')
      } catch (error) {
        console.log('⚠️  Database setup failed - you can run it later with: npm run db:push')
      }
    } else {
      console.log('⏭️  Skipping database setup - run `npm run db:push` when ready')
    }
    
    // Setup complete
    console.log('\n🎉 Setup completed successfully!')
    console.log('\n📋 Next steps:')
    console.log('1. Update .env.local with your Gemini API key')
    console.log('2. Ensure PostgreSQL is running')
    console.log('3. Run database setup: npm run db:push')
    console.log('4. Start development:')
    console.log('   Terminal 1: npm run dev      (Frontend - port 3002)')
    console.log('   Terminal 2: npm run server   (Backend - port 3001)')
    console.log('\n🌐 Open http://localhost:3002 to start transcribing!')
    
  } catch (error) {
    console.error('❌ Setup failed:', error.message)
    process.exit(1)
  } finally {
    rl.close()
  }
}

// Run setup
setupProject()